### PR TITLE
deleting files

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable-dev-chris-default-rtdb.firebaseapp.com/reviews/cgiroux86/test-repo/3)

### CODE REVIEW

**Review by belowabove — COMMENTED** [review]
This is a test

> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test-repo/3#-:-MSEoGbN9XDHILIOv48B:b5wkefe)* status: 0 of 2 files reviewed, all discussions resolved

**Review by belowabove — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test-repo/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test-repo/3#-MSEoixoBKitf1215GcR:-MSEoixoBKitf1215GcS:b-quqi2u) (no related file):*
The file is empty!

---

**Review by belowabove — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test-repo/3)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test-repo/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @belowabove)

*[a discussion](http://localhost:8080/reviews/cgiroux86/test-repo/3#-MSEoixoBKitf1215GcR:-MSEsuI_3wHOrYb3sPja:b-896fix) (no related file):*
<details><summary><i>Previously, belowabove wrote…</i></summary><blockquote>

The file is empty!
</blockquote></details>

Done.

---

**Review by cgiroux86 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test-repo/3)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @belowabove)

**Review by belowabove — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](http://localhost:8080/reviews/cgiroux86/test-repo/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
